version: '3.9'

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql/
    env_file:
      - .env
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: always

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kjaco/database
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kjaco/wordpress
